### ISSUE TITLE
Filter out suspended threads from CPU hotpaths profiler

### ISSUE THREAD

**Issue by ogxd** [dr-dotnet/dr-dotnet#83]
# Context

The main goal CPU hotpaths profiler is to list the CPU hotpaths, in an inclusive percentage of CPU usage. Currently, the way this profiler works is by iterating over callstacks for all managed threads at a fixed time interval. While this approach gives quite accurate results of what threads are doing for a very small overhead, it lists callstacks for working threads as well as for suspended threads. Having suspended threads callstacks mixed in the results dilutes where the actual CPU power is being spent on.   

This is not trivial. In fact, most CPU profilers don't offer this feature.

# Solutions

Find a way to filter out suspended thread from the analysis.  

### Use [RuntimeThreadSuspended/Resumed](https://learn.microsoft.com/en-us/dotnet/framework/unmanaged-api/profiling/icorprofilercallback-runtimethreadresumed-method) callbacks
This approach as several drawbacks:

- It requires one more profiling flag `COR_PRF_MONITOR_THREADS` (and possibly a costly one)
- It complexity the code quite a bit
- Since we already suspend the runtime to take the stacks snapshots, we need to disambiguate threads suspended because of this pause

### Call the OS API to know if a thread is suspended
- No straightforward on linux and macos.
- Possibly quite resource intensive
- It would complexity the code quite a bit and make the profiler OS-dependent.

### Use context information to (approximately) tell if a thread is suspended
Inspired from this: https://www.usenix.org/legacy/publications/library/proceedings/coots99/full_papers/liang/liang_html/node10.html

# Todo

- [x] Factorize the way we take stack snapshot to ease implementations (with trait?)
- [x] Add profiler parameter (default is filter out suspended threads)
- [x] BONUS: Refactor to use Tree structure

**Comment by ogxd** [comment]
Before:
![image](https://github.com/dr-dotnet/dr-dotnet/assets/12692438/2fddf084-cdb4-40ca-9d08-6aaac9e63a09)

After, but with filtering disabled:
<img width="1607" alt="image" src="https://github.com/dr-dotnet/dr-dotnet/assets/12692438/00fcbfd0-30e6-4a4e-acb8-d293a7d9a582">

After, with filtering enabled and using instruction pointer to detect suspended threads:
<img width="1614" alt="image" src="https://github.com/dr-dotnet/dr-dotnet/assets/12692438/df56b899-90f1-43c1-91a4-db2939a066a0">

After, with filtering enabled and using register context hash to detect suspended threads:
<img width="1608" alt="image" src="https://github.com/dr-dotnet/dr-dotnet/assets/12692438/cebdc6c0-e4a0-494e-b49d-771cfa75c7f2">

I'm not sure which is the most accurate way of filtering out suspended threads

**Comment by ogxd** [comment]
I also took the opportunity to make use of the Tree structure. It has several benefits:
- Simplifies the CPU hotpaths profiler code
- Fixes the HTML report layout issue(s?)
- Build tree using Function IDs, and only compute method names at the end, and far less times (once per `TreeNode`)

I also write the HTML report from the thread, as it simplifies a lot the borrowing boilerplate stuff required by the Rust borrow checker when dealing with thread shared resources.
